apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backendapp.name }}
  labels: 
    group: {{ .Values.backendapp.group }}
spec:
  type: {{ .Values.backendapp.service.type }}
  selector:             
    app: {{ .Values.backendapp.name }}
  ports:
    - port: {{ .Values.backendapp.service.port }}       
      targetPort: {{ .Values.backendapp.container.port }}  